x-rendertron-base: &rendertron-base
  image: dockette/rendertron
  tmpfs:
    - /tmp:rw,size=512m,mode=1777
  shm_size: "1g"
  restart: unless-stopped
  logging:
    options:
      max-size: "1m"

services:
  www-render-0:
    <<: *rendertron-base
    expose:
      - "3000"

  www-render-1:
    <<: *rendertron-base
    expose:
      - "3000"

  www-render-2:
    <<: *rendertron-base
    expose:
      - "3000"

  www-render-nginx:
    image: fabiocicerchia/nginx-lua:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - www-render-0
      - www-render-1
      - www-render-2