services:
  haproxy:
    image: haproxy:3.2-alpine
    container_name: www-render-haproxy
    restart: unless-stopped
    expose:
      - "8080"
      - "8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro