services:
  haproxy:
    build: .
    container_name: render-haproxy
    restart: unless-stopped
    expose:
      - "8080"
      - "8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro